version: "3.8"
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    env_file:
      - ../.env
    depends_on:
      - mysql
      - redis
    network_mode: service:mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pokemondb}
    ports:
      - "3306:3306"
    env_file:
      - ../.env

  redis:
    image: redis:7
    restart: unless-stopped
    network_mode: service:mysql
    env_file:
      - ../.env
