version: "3.8"
services:
  dev:
    image: mcr.microsoft.com/devcontainers/go:1
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
      - MYSQL_DATABASE=appdb
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - devnet

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    networks:
      - devnet

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
